### ISSUE TITLE
[Suggestion] Add a copy button

### ISSUE THREAD

**Issue by Shywim** [ypinskiy/GBF-Raiders#12]
Adding a copy button beside the raid ID would be a nice little addition for faster copy and because on every browser I tested (Firefox on Windows & Android and my default device browser on Android) the constant refresh make it near imposible to copy the raid ID.

**Comment by ypinskiy** [comment]
Tapping or clicking on the raid row itself as well as clicking on desktop notifications will also copy the ID to the clipboard. Were you aware of this functionality? If you were, does this not work for you?

**Comment by Shywim** [comment]
Ah sorry I didn't know and I skipped this in the help section. I will pay more attention next time 😅
