### ISSUE TITLE
Button to reset service worker

### ISSUE THREAD

**Issue by luminairre** [ypinskiy/GBF-Raiders#25]
Hi!

I know there are lots of updates recently, for some reason the service worker is not cleared when I cmd-shift-r (not sure if this is the default behavior or what). I had to use developer tool and unregister the service worker to get all updates.

It might be a good idea if you include a "force refresh" button in settings that unregister the service worker (and probably append the css/js with timestamp to force refresh them).

**Comment by ypinskiy** [comment]
I am going to rework the Help button tomorrow, part of that will be to move some debugging stuff to that including reseting the site/unregistering service worker.

**Comment by ypinskiy** [comment]
Removed service worker in commit 6f21f88b7e4b060d056506242c5ecc21d7a8e112
