### ISSUE TITLE
"autoInstall" should be false in semantic.json

### ISSUE THREAD

**Issue by trim21** [ypinskiy/GBF-Raiders#26]
There are some errors in semantic.json...
old files in `static/semantic/dist/` is correct, but when i run `npm i`, new files of semaintic will be gen automatically and overwrite old files.

**Comment by ypinskiy** [comment]
This is not an issue, the setting is not wrong, you just want it different. Fork the project and then change the setting in the local project.

**Comment by Trim21** [comment]
It's not that 'I just want it different'. I followed the readme and try to run it locally at commit [`d5bc2a`.](https://github.com/ypinskiy/GBF-Raiders/commit/d5bc2a874bc49e4610f441af7eb2fbb6f8838ba5)

In readme, it says that "Semantic UI is set to automatically install itself during this process".  When I run `npm i`, semantic install itself indeed. But when I run `npm run start` and open browser before I change any code, It looks like this

![image](https://user-images.githubusercontent.com/13553903/37501423-4ff567f0-2909-11e8-8954-6bf95e75d564.png)

`$(...).popup` is a function of Semantic UI, but module popup is not listed in semantic.json and it doesn't work.

It seems that Semantic isn't set to automatically install itself, and I'm not sure how to correct the setting of semantic, so i suggest to set it to false as there have been files compiled correctly

**Comment by ypinskiy** [comment]
Did you get any `gulp` errors? Try installing `semantic-ui` separately with npm and see if it actually finishes building everything. My files are also overwritten on update and yet the site does not have this issue, thus, this points to something different with your dev environment.

**Comment by Trim21** [comment]
There isn't any error when I install deps.

It looks that your files of website are not overwritten....

https://www.gbfraiders.com/semantic/dist/semantic.min.js
```
 /*
 * # Semantic UI - 2.2.13
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
```
same with the file in git commit

in `package.json`
```
"semantic-ui": "^2.3.0",
```

my file i just build:
```
 /*
 * # Semantic UI - 2.3.0
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
```

**Comment by ypinskiy** [comment]
I'll look into this then. Perhaps the popup module isn't there by default in 2.3.0 and I need to add it in.
