### ISSUE TITLE
[Feature Request] Removal of unnecessary pop up

### ISSUE THREAD

**Issue by Xhiro-Yui** [ypinskiy/GBF-Raiders#27]
![image](https://user-images.githubusercontent.com/19362381/37563614-b4d38a46-2abf-11e8-942a-ea3c45f9fe09.png)

This pop-up is rather unnecessary and actually just bothers me (probably lots of others too) when rushing raids. Can this be disabled or displayed by changing the button instead?

**Comment by ypinskiy** [comment]
Added setting to control popups in commit 81adfabf9b9fdebf339eabb142945fe69615d05c. Should be live now.
