### ISSUE TITLE
Re-deploying problem to heroku

### ISSUE THREAD

**Issue by luminairre** [ypinskiy/GBF-Raiders#4]
Hi!

So I managed to launch an instance in heroku, but I have a problem, everytime I want to redeploy, I have to deploy to a new dyno, deploying to an already existing dyno gets me this error:

` npm ERR! Cannot read property '0' of undefined`

I mean, going forward if there are any changes, this can be a bit difficult to update my fork

Thank you!

**Comment by ypinskiy** [comment]
How are you redeploying? Using the deploy button in the GitHub page or through Heroku's dashboard?

**Comment by luminairre** [comment]
I was redeploying through Heroku's dashboard, I'm deploying through there too, not using the button.
I realized this when I was redeploying after some modifications. However, deploying a new dyno using the same commit works.

Here's the redeploy build log:

`-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  8.1.2
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.1.2...
       Downloading and installing node 8.1.2...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 5.0.3)...
       npm 5.4.2 installed
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! Cannot read property '0' of undefined
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2017-10-06T00_37_25_128Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

**Comment by ypinskiy** [comment]
Seems to be an issue with any NPM above version 5.0.x. Try one of the solutions mentioned [here.](https://github.com/npm/npm/issues/17858).

**Comment by luminairre** [comment]
Thanks, submitting a fix
