### ISSUE TITLE
UI Dimmer missing in page

### ISSUE THREAD

**Issue by jesuscc1993** [ypinskiy/GBF-Raiders#41]
When pressing the "settings" button on a raid, nothing seems to happen.
When opening the console, it can be seen that each time the button is pressed the following error is thrown:
`semantic.min.js:11 Modal: UI Dimmer, a required component is not included in this page`

**Comment by ypinskiy** [comment]
My initial tests don't show this error on any of my computers but I will investigate further. In the meanwhile can you try the following troubleshooting steps one at a time:

1. Please see if any adblocker or privacy extension is running and try turning it off and refreshing the site.

2. There is a Reset Site button in the help popup. Try pressing that and then refreshing the page.

3. Open the browser's devtools using Ctrl + Shift + J and then go to the Application tab. Click on the Clear Site Data tab and button and then refresh the page.

4. If all of these steps fail to help,  refresh the page, open the devtools, go to the console, use the site for a bit including opening settings, and then copy/paste everything in the console into a Google Doc/gist/Pastebin/etc and put the link here for me to check.

**Comment by jesuscc1993** [comment]
1. I have uBlock Origin and Poper Blocker, but they both have raiders on their whitelist and it used to work like that before.
2. I know, I had tried it. It resetted the site to default settings but the issue persisted.
3. Just tried this, but the results were the exact same as pressing the "Reset Site" button.
4. Log attached.

Additional info:
Tested on Chrome 78.0.3904.108 on a Win10 machine.
Also tested on Firefox 70.0.1, where I had never previously opened the site, and had the issue right from the beginning.

**Comment by ypinskiy** [comment]
0cc4ce8890077ba4142fd375d0c7a0c8ad7faa24 I added the Dimmer UI element in this commit, that should fix it for now. Please try reseting/refreshing the site again and seeing if it works now.

**Comment by jesuscc1993** [comment]
I repeated all my tests after your comment, but I keep getting the same error. Are you sure the change was deployed?
I additionally tried the site in Edge, where I don't have any extensions (only used it to download Chrome), and the settings popup doesn't work there either so we can rule out extensions being the issue.

**Comment by ypinskiy** [comment]
I definitely deployed it, when I log into the server I can see the component sitting there in its proper folder. This is a strange issue. It seems like the site is still being cached and using an old version but the logs show the new version number. I will still look into this issue, but I suggest for now that you use one of the other raidfinders until I can fix this.

**Comment by jesuscc1993** [comment]
Any updates on this?
I'm still having the issue.

**Comment by jesuscc1993** [comment]
Closing issue as [server](https://www.gbfraiders.com) is dead.
