### ISSUE TITLE
twitter formatting changed

### ISSUE THREAD

**Issue by zhurai** [ypinskiy/GBF-Raiders#9]
twitter formatting changed as of about an hour ago (41 min ago?)  (in this software, it's showing up, but the raid id isn't scraped correctly)

参加者募集！参戦ID: **id raid**

-> 

**id** :参戦ID 参加者募集！**raid**

**Comment by ypinskiy** [comment]
Fixed in commit 8554cbe

**Comment by zhurai** [comment]
forgot to mention it's the same format for the english version as well (just the kanji is replaced with english...) e.g.

**ID** :Battle ID
I need backup!
**RAID**

format

**Comment by ypinskiy** [comment]
Yep, accounted for that as well, it should be all good now.
